FROM php:7.3-fpm

RUN apt update && \
    apt install -y \
    libpng-dev && \
    printf "\n" | pecl install -o -f redis && \
    rm -rf /tmp/pear && \
    docker-php-ext-configure gd && \
    docker-php-ext-install gd pcntl opcache && \
    docker-php-ext-enable redis opcache

