apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-worker
  labels:
    {{- include "chart.workerLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabelsWorker" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.workerLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- include "chart.volumes" . | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "fpm_image" . }}"
          command: ["/usr/local/bin/php"]
          args: ["artisan", "requests:fetcher"]
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          env:
          {{- include "chart.env" (dict "root" .) | nindent 10 }}
          volumeMounts:
          {{- include "chart.mounts.env" . | nindent 10 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - pgrep
              - -f
              - requests:fetcher
          readinessProbe:
            exec:
              command:
              - pgrep
              - -f
              - requests:fetcher
          startupProbe:
            exec:
              command:
              - pgrep
              - -f
              - requests:fetcher
          resources:
            requests:
              {{- toYaml .Values.resources.requests.worker | nindent 14 }}
            limits:

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: {{ .Release.Name }}-worker
                topologyKey: kubernetes.io/hostname
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
