<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use LaravelLocalization;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redis;
use Illuminate\Support\Facades\Validator;

/**
 * Before we redirect users to the affiliate shops we will track the clicks ourself.
 * Reason is that many Affiliate shops redirect to invalid URLs (404, 500, ... Errors) which leads to bad user experience.
 * We will store the clicked Affiliate Link together with the final URL the user should land on.
 * No userdata or other metadata will be stored together with that information.
 * 
 * That way we can do manual validation of affiliate links and exclude bad partnershop links to be shown in the future. Since this will be
 * a lot of links we count the clicks so we can validate the most used ones first.
 */

class AdgoalController extends Controller
{
    # Data will be stored for 7 days
    const STORAGE_DURATION_HOURS = 24 * 7;
    const REDIS_STORAGE_KEY = "affiliate_click";
    const REDIS_BLACKLIST_KEY = "affiliate_blacklist";

    /**
     * This function is called when a user clicks on a affiliate link. It will first validate that the URL
     * was generated by us to prevent random redirect links to be manually created for our domains.
     * After that we will store the necessary information (link and affiliate link) into our database.
     * After that we will redirect the user to the affiliate shop
     */
    public function forward(Request $request)
    {
        /**
         * Get Parameters (Result informations)
         * 1. affillink (With Affiliate Redirect)
         * 2. link
         * 5. Password (hmac with adgoal private key and the two parameters)
         */
        $request->validate([
            'affillink' => ['required', 'url', 'active_url'],
            'link' => ['required', 'url', 'active_url'],
            # Validation of redirect request so that one cannot generate random redirect URLs pointing to our domains
            'password' => function ($attribute, $value, $fail) use ($request) {
                // Check if hmac matches
                $correctPassword = self::generatePassword($request->input('affillink'), $request->input('link'));
                if (!hash_equals($correctPassword, $value)) {
                    $fail('The given password is incorrect!');
                }
            }
        ]);

        $this->storePartnerCallFast($request->input('affillink'), $request->input('link'));

        return redirect($request->input('affillink'), 301, [
            "Referrer-Policy" => "no-referrer-when-downgrade"
        ]);
    }

    /**
     * Stores Click information into Redis Cache for fast execution since this is synchronous call
     * at search time.
     * A Cronjob will pick the data up and store it into Mariadb later (see self::storePartnerCall)
     */
    private function storePartnerCallFast($affillink, $link)
    {
        # Generate Data to store
        $host = parse_url($link, PHP_URL_HOST);
        if (empty($host)) {
            return;
        }
        $storeObject = [
            "host" => $host,
            "affillink" => $affillink,
            "link" => $link,
        ];


        # Store Data in Redis
        $redis = Redis::connection(config('cache.stores.redis.connection'));
        $redis->rpush($this::REDIS_STORAGE_KEY, json_encode($storeObject));
    }

    public static function storePartnerCalls()
    {
        $redis = Redis::connection(config('cache.stores.redis.connection'));
        DB::transaction(function () use ($redis) {
            while (!empty($data = $redis->lpop(self::REDIS_STORAGE_KEY))) {
                $data = json_decode($data, true);
                # Insert data into mariadb table
                DB::insert(
                    'insert into affiliate_clicks (hostname, affillink, link) values (?, ?, ?)',
                    [$data["host"], $data["affillink"], $data["link"]]
                );
            }
        });
    }

    /**
     * Generates a Redirect URL for our partnershops
     */
    public static function generateRedirectUrl($affillink, $link)
    {
        $password = self::generatePassword($affillink, $link);
        return route('adgoal-redirect', ["link" => $link, "affillink" => $affillink, "password" => $password]);
    }

    /**
     * Generates hmac password to validate redirect URLs
     */
    public static function generatePassword($affillink, $link)
    {
        return hash_hmac("sha256", $affillink . $link, config('metager.metager.adgoal.private_key'));
    }


    /**
     * Routes for the Admin Interface
     */
    // ...existing code...
}