<?php

/**
 * Anonyme Token — /hilfe/anonyme-token.
 *
 * Aus dem "anonymous-token"-Zweig von pass/lang/<locale>/help.json.
 * Der Pfad /keys/help/anonymous-token wird dauerhaft hierher weitergeleitet:
 * er steht in bereits versandten Mitglieds-Willkommensmails.
 */

return [
    "heading" => "Anonymous tokens",
    "description" => [
        "heading" => "What are anonymous tokens?",
        "text" => "If you use a MetaGer key, you will receive a randomly generated password that your browser sends to us with each search query so that we can enable ad-free search. If you use our <a href=\"/app\" target=\"_blank\">Android app</a>, or our web extension for <a href=\"https://chrome.google.com/webstore/detail/gjfllojpkdnjaiaokblkmjlebiagbphd\" target=\"_blank\" rel=\"noopener\">Chrome</a> and <a href=\"https://addons.mozilla.org/firefox/addon/metager-suche/\" target=\"_blank\" rel=\"noopener\">Firefox</a>, instead of the password, your browser sends us a randomly generated password (anonymous token) with each search request for authentication, which is generated locally. This ensures that each password is unique and has no connection with the actual MetaGer key, nor between the individual passwords.",
    ],
    "problem" => [
        "heading" => "What problem are anonymous tokens supposed to solve?",
        "text" => "If your browser always sends us the same password with every search query, we would at least theoretically have the possibility to establish a correlation between all searches performed with the same key. Even if we don't do that, of course, trust would still be necessary to be sure of your anonymous search. So that we do not only have to promise the anonymous search, but can also prove it, we have introduced the anonymous tokens.",
    ],
    "general-function" => [
        "heading" => "How does it work?",
        "texts" => [
            "So we want to have one-time passwords generated directly from your endpoint device, which you then send to us for authentication during your searches. However, for each anonymous token on your end device, we need to make sure that a regular token has been subtracted from your MetaGer key for it, without (and this is the crux) telling us which MetaGer key was used to generate the anonymous token.",
            "Traditionally, we would use some form of cryptographic signature for this purpose. In this case, we would sign the generated anonymous token. Then, when you send us the anonymous token along with the signature at a later time, we can be sure that the anonymous token is valid. However, to get the signature, you would have sent us the anonymous token along with your real key, which would nullify the anonymity.",
            "Therefore, we use a modified form of cryptographic signature instead, the so-called <a href=\"https://en.wikipedia.org/wiki/Blind_signature\" target=\"_blank\">blind signature</a>. To create a real-life analogy, it's like sending us your anonymous token in a carbon paper envelope. In this example, we would not be able to open the envelope, but we would be able to sign from the outside, so our signature would be transferred to the anonymous token inside. When you get the envelope back, you could remove it and send us the password and signature back later. We could then confirm that it is indeed our signature.",
            "In fact, this analogy is a bit misleading, because in the actual process, at the moment you send us the anonymous token and the signature, we have not only never seen the anonymous token before, but also never seen the signature itself. And yet we can verify that the signature was generated by us.",
        ],
    ],
    "meaning" => [
        "heading" => "What does this mean for your authenticated searches?",
        "texts" => [
            "By using the described algorithm, we and you alike can ensure that a new random password unrelated to your MetaGer key is used each time for your authenticated searches.",
            "The special thing about this algorithm is that all components that ensure anonymity are executed locally on your device. This executed source code can be viewed and verified by anyone at any time.",
            "Best of all, you don't need to configure anything to use anonymous tokens. Simply installing/using our browser extension/Android app is enough to make your device use anonymous tokens for all searches.",
        ],
    ],
    "technical-function" => [
        "heading" => "The algorithm behind it:",
        "texts" => [
            "In a classic RSA signature, we would take the anonymous token <code>m</code>, the secret exponent <code>d</code>, and the public modulus <code>N</code> of our private key and create the signature using <code>m^d (mod N)</code>. However, we want <code>m</code> to remain secret.",
            "Therefore, your terminal creates a random number <code>r</code> using a random number generator, which is divisor-unrelated to <code>N</code>. So the greatest common divisor of <code>r</code> and <code>N</code> must be <code>1</code>.",
            "Because <code>r</code> is a random number, it follows that <code>m'</code> does not reveal any information about the locally stored anonymous token <code>m</code>.",
            "Our server now receives the obfuscated anonymous token <code>m'</code> from your end device together with the MetaGer key to be used. We subtract a token from the key and send the also obfuscated signature <code>s'&Congruent; (m')^d (mod N)</code> back to your end device.",
            "Your terminal can now compute the actual valid RSA signature <code>s</code> for the unencrypted anonymous token: <code>s&Congruent; s' r^-1 (mod N)</code>. This works because for RSA keys, <code>r^(e*d)&Congruent; r (mod N)</code>. And therefore also: <code>s &Congruent; s' * r^-1 &Congruent; (m')^d*r^-1 &Congruent; m^d*r^(e*d)*r^-1 &Congruent; m^d*r*r^-1 &Congruent; m^d (mod N)</code>.",
            "Your end device now sends us the unencrypted anonymous token together with the associated signature for authorization during a search. The key itself is no longer sent to us during the search.",
        ],
    ],
];
