<?php
return [
    "title" => 'MetaGer - Ajuda fàcil',
    "backarrow" => 'Enrere',
    'glossary' => 'Fent clic al símbol<a title="Aquest símbol porta al glossari" href="/hilfe/easy-language/glossary"><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> podeu accedir a l\'explicació de les paraules difícils.',

    "datenschutz" => [
        "title" => "Anonimat i seguretat de les dades",
        "1" => 'Galetes de rastreig, identificadors de sessió i adreces IP',
        "2" => 'A MetaGer sou anònims. <br> Això vol dir que no se us reconeix. <br> No desem cap dada que permeti identificar ningú. <br> Per a això oferim 2 funcions: <br> el servei ocult de Tor<a title="Amb això podeu cercar amb seguretat. Feu clic per a més informació" href="/hilfe/easy-language/glossary#gltorhidden" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> i <br> obre anònimament<a title="Una persona és anònima. Així, ningú no sap qui és. Feu clic aquí per a més informació" href="/hilfe/easy-language/glossary#glopenanonymously" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a>',
        "3" => 'Trobareu més informació sobre el tema a <a href="/hilfe/easy-language/privacy-protection#eh-torhidden">Servei ocult de Tor</a>. <br> Per saber-ne més sobre <strong>obre anònimament</strong><a title="Una persona és anònima. Així, ningú no sap qui és. Feu clic aquí per a més informació" href="/hilfe/easy-language/glossary#glopenanonymously" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a>, mireu <a href="/hilfe/easy-language/privacy-protection#eh-proxy">el servidor intermediari de MetaGer</a>. <br> Podeu accedir a aquestes funcions des de <strong>Serveis</strong>, a la barra de navegació.',
    ],
    "tor" => [
        "title" => "Servei ocult de Tor",
        "1" => 'El servei ocult de Tor<a title="Amb això podeu cercar amb seguretat. Feu clic per a més informació" href="/hilfe/easy-language/glossary#gltorhidden" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> és la manera més segura de fer servir MetaGer. <br> Ara bé, us cal el navegador Tor<a title="Un navegador per a la web fosca. Feu clic per a més informació." href="/hilfe/easy-language/glossary#gltorbrowser" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a>. <br> Podeu baixar el navegador Tor<a title="Un navegador per a la web fosca. Feu clic per a més informació." href="/hilfe/easy-language/glossary#gltorbrowser" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> aquí: <br><a href=\"https://www.torproject.org/\" target=\"_blank\" rel=\"noopener\">https://www.torproject.org</a>. <br> Un cop tingueu el navegador Tor, podeu fer servir el servei ocult de Tor<a title="Amb això podeu cercar amb seguretat. Feu clic per a més informació" href="/hilfe/easy-language/glossary#gltorhidden" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> aquí: <br><a href=\"https://metager.de/tor/\" target=\"_blank\" rel=\"noopener\">https://metager.de/tor</a>.',
        "2" => 'Podeu accedir a MetaGer des del navegador Tor<a title="Un navegador per a la web fosca. Feu clic per a més informació." href="/hilfe/easy-language/glossary#gltorbrowser" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> amb aquest enllaç: <br> http://metagerv65pwclop2rsfzg4jwowpavpwd6grhhlvdgsswvo6ii4akgyd.onion',
    ],
    "proxy" => [
        "title" => "Servidor intermediari de MetaGer (obre anònimament)",
        "1" => 'Amb la nostra funció «obre anònimament» podeu obrir pàgines web de manera anònima. <br> Això vol dir que no se us reconeix. <br> «Obre anònimament»<a title="Una persona és anònima. Així, ningú no sap qui és. Feu clic aquí per a més informació" href="/hilfe/easy-language/glossary#glopenanonymously" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a> funciona com un escut protector. <br> Si voleu cercar de manera anònima, seguiu aquests passos: <br> als resultats de cerca hi ha un botó <strong>obre anònimament</strong><a title="Una persona és anònima. Així, ningú no sap qui és. Feu clic aquí per a més informació" href="/hilfe/easy-language/glossary#glopenanonymously" ><img class="glossary-icon lm-only" src="/img/glossary-icon-lm.svg"/><img class="glossary-icon dm-only" src="/img/glossary-icon-dm.svg"/></a>. <br> El botó té aquest aspecte:',
        "2" => "Quan feu clic al botó, s'obre una finestra nova. <br> Ja hi surt la pàgina on heu fet clic. <br> Aquesta finestra té el seu propi navegador. <br> Aquest navegador funciona amb seguretat als nostres servidors. <br> No al vostre dispositiu. <br> La pàgina web no pot saber qui sou. <br> Aquest navegador té la seva pròpia barra d'adreces i les seves pestanyes. <br> Els podeu fer servir com sempre. <br> Esteu protegits tota l'estona. <br> Quan tanqueu la finestra, tot s'esborra.",
    ],
    "content" => [
        'title' => 'Contingut qüestionable / protecció de menors',
        "explanation" => [
            '1' => 'Si trobeu a internet contingut que sembli prohibit, el podeu denunciar. <br> Envieu un correu a <a href="mailto:hotline@jugendschutz.net" target="_blank" rel="noopener">hotline@jugendschutz.net</a>. <br> Alternativament, visiteu <a href="http://www.jugendschutz.net/" target="_blank" rel="noopener">www.jugendschutz.net</a> i empleneu el formulari de denúncia. ',
            '2' => 'Si trobeu contingut prohibit a MetaGer, feu-nos-ho saber. <br> Envieu un correu a <a href="mailto:jugendschutz@metager.de" target="_blank" rel="noopener">jugendschutz@metager.de</a>.',
        ],
    ],
];
