ingress:
  hosts:
    - host: metager.de
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager.org
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager.es
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - metager.de
        - metager.org
        - metager.es
      secretName: metager-tls

autoscaling:
  maxReplicas: 100
