ingress:
  hosts:
    - host: metager.de
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.metager.de
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager2.de
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.metager2.de
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager.org
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.metager.org
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager.es
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.metager.es
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager.nl
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.metager.nl
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: metager.co.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.metager.co.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - metager.de
        - www.metager.de
        - metager2.de
        - www.metager2.de
        - metager.org
        - www.metager.org
        - metager.es
        - www.metager.es
        - metager.nl
        - www.metager.nl
        - metager.co.uk
        - www.metager.co.uk
      secretName: production-tls
autoscaling:
  minReplicas: 2

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

resources:
  requests:
    fpm:
      cpu: 1
      memory: 500M
    scheduler:
      cpu: 50m
      memory: 50M
    worker:
      cpu: 1
      memory: 100M
    queue:
      cpu: 50m
      memory: 50M
    nginx:
      cpu: 100m
      memory: 100M
    reverb:
      cpu: 50m
      memory: 50M

redis-sentinel:
  replicaCount: 3
  redis:
    persistence:
      enabled: false
