<?php

return [
    "title"	=>	"Ayuda de MetaGer",

    "backarrow"             => 'Volver',

    "datenschutz.title" => "Anonimato y seguridad de los datos",
    "privacy.1" => "Cookies de seguimiento, identificadores de sesión y direcciones IP",
    "datenschutz.2" => 'Nada de esto se utiliza, almacena, levanta o procesa de alguna manera aquí en MetaGer (excepción: almacenamiento a corto plazo contra ataques de hackers y bots). Como consideramos que este tema es extremadamente importante, también hemos creado opciones que pueden ayudarte a conseguir el máximo nivel de seguridad: el Servicio Oculto TOR de MetaGer y nuestro servidor proxy anonimizador',
    "datenschutz.3" => "Puede encontrar más información a continuación. Se puede acceder a las funciones en \"Servicios\" en la barra de navegación",
    "tor.title" => "Servicio oculto de Tor",
    "tor.1" => "MetaGer lleva muchos años ocultando las direcciones IP y no las almacena. Sin embargo, estas direcciones son temporalmente visibles en el servidor de MetaGer mientras se ejecuta una búsqueda: por lo que si MetaGer se viera comprometido alguna vez, este atacante podría leer sus direcciones y guardarlas. Para satisfacer la mayor necesidad de seguridad, mantenemos una instancia de MetaGer en la red Tor: el servicio MetaGer-TOR-hidden - accesible a través de: <a href=\"/tor/\" target=\"_blank\" rel=\"noopener\">https://metager.de/tor/</a>. Necesitará un navegador especial para utilizarlo, que puede descargar de <a href=\"https://www.torproject.org/\" target=\"_blank\" rel=\"noopener\">https://www.torproject.org/</a>.",
    "tor.2" => "Se puede llegar a MetaGer en el navegador Tor en: http://metagerv65pwclop2rsfzg4jwowpavpwd6grhhlvdgsswvo6ii4akgyd.onion ",
    "proxy.title" => "Anonimizar el servidor proxy de MetaGer",
    "proxy.1" => "Para utilizarlo, todo lo que tienes que hacer en la página de resultados de MetaGer es hacer clic en \"ABRIR ANONIMO\" en la parte inferior de los resultados. A continuación, su solicitud se dirigirá al sitio web de destino a través de nuestro servidor proxy de anonimización y sus datos personales permanecerán totalmente protegidos. Importante: si sigue los enlaces de las páginas a partir de este punto, seguirá protegido por el proxy. Sin embargo, no se puede ir a una nueva dirección en el campo de dirección anterior. En este caso, perderá la protección. También puede ver si todavía está protegido en el campo de la dirección. Muestra: https://proxy.suma-ev.de/?url=hier es la dirección real.",
    "maps.title" => "MetaGer Maps",
    "maps.1" => 'Salvaguardar la privacidad en la era de los pulpos de los datos globales también nos ha llevado a desarrollar: <a href="https://maps.metager.de" target="_blank">https://maps.metager.de</a>.  El único (hasta donde sabemos) planificador de rutas que ofrece una funcionalidad completa a través del navegador y la aplicación, sin almacenar las ubicaciones del usuario. Todo esto es verificable, porque nuestro software es de código abierto. Para el uso de maps.metager.de recomendamos nuestra versión de aplicación rápida. Puede descargar nuestras aplicaciones en <a href="/app" target="_blank">obtener una aplicación</a> (o, por supuesto, a través de Play Store)',
    "maps.2" => "A esta función de mapa también se puede acceder desde la búsqueda de MetaGer (y viceversa). En cuanto busques un término en MetaGer, verás un nuevo foco de búsqueda \"Mapas\" en la parte superior derecha. Al hacer clic en él, se accede a un mapa asociado",
    "maps.3" => "Después de llamar al mapa, muestra los puntos encontrados por MetaGer (POIs = Puntos de Interés) también mostrados en la columna de la derecha. Al acercarse, esta lista se adapta a la sección del mapa. Si mantiene el ratón sobre un marcador en el mapa o en la lista, se resalta el correspondiente homólogo. Haga clic en \"Detalles\" para obtener información más detallada sobre este punto a partir de la base de datos que aparece a continuación",    
    'content.title' => 'Contenido cuestionable / Control parental',
    'content.explanation.1' => 'He recibido "hits", no sólo me resultan molestos, sino que en mi opinión tienen contenido ilegal!',
    'content.explanation.2' => 'Si encuentras algo en Internet que crees que es ilegal o perjudicial para los menores, puedes ponerte en contacto con <a href="mailto:hotline@jugendschutz.net" target="_blank" rel="noopener">hotline@jugendschutz.net</a> por correo electrónico o ir a <a href="http://www.jugendschutz.net/" target="_blank" rel="noopener">www.jugendschutz.net</a> y rellenar el formulario de denuncia que se encuentra allí. Tiene sentido exponer brevemente lo que considera inaceptable y cómo ha llegado a esta oferta. También puede informarnos directamente de los contenidos dudosos. Para ello, escribe un correo electrónico a nuestro responsable de la protección de los jóvenes (<a href="mailto:jugendschutz@metager.de" target="_blank" rel="noopener">jugendschutz@metager.de</a>).',
];