.build_composer:
  stage: build_composer
  image: $BUILD_DOCKER_IMAGE
  variables:
    IMAGE_NAME: fpm
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $CI_REGISTRY_IMAGE
    - docker build --network=host
        --target=composer
        -f build/fpm/Dockerfile
        -t ${CI_REGISTRY_IMAGE}/fpm:$IMAGE_TAG .
    - docker push ${CI_REGISTRY_IMAGE}/fpm:$IMAGE_TAG
  after_script:
    - docker logout $CI_REGISTRY

build_composer_review:
  extends:
    - .build_composer
  variables:
    IMAGE_TAG: $CI_COMMIT_REF_SLUG
